### ISSUE TITLE
望潮6.30出现问题  ，6.25正常运行

### ISSUE THREAD

**Issue by klcb2010** [Bidepanlong/ql#3]
6.30 异常

`🚀登录成功：读友_BTHdf9
Traceback (most recent call last):
  File "Py-Fuscate", line 75, in login
TypeError: 'dict_itemiterator' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/Bidepanlong_ql/bd_wc.py", line 20, in <module>
    exec(marshal.loads(zlib.decompress(
  File "Py-Fuscate", line 1, in <module>
  File "Py-Fuscate", line 1, in <module>
  File "Py-Fuscate", line 1, in <module>
  File "Py-Fuscate", line 1, in <module>
  File "Py-Fuscate", line 381, in <module>
  File "Py-Fuscate", line 75, in login
TypeError: 'dict_itemiterator' object is not subscriptable

## 执行结束... 2023-07-04 19:55:36  耗时 7 秒　　　　　`

**Comment by Bidepanlong** [comment]
需要py版本3.10以上
